[package]
name = "baton-tetra"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baton = { path = "../baton" }
tetra = { version = "0.6.5", default-features = false }
